### ISSUE TITLE
伟大的哥谭市蒙面人

### ISSUE THREAD

**Issue by Aki-Tomoya** [ch3cook-fdu/NumPytorch#1]
尊敬的蝙蝠侠先生：
        您发表的文章End-to-End 3D Dense Captioning with Vote2Cap-DETR深得我哥谭市小市民喜欢，为了彻底搞懂，已经看了好几遍这篇论文，但是无奈文章中的github仓库链接过了好几个月了还是查无此库。
        这篇文章非常有意思，特别是对3D特征信息处理的方面，私认为在3D Dense captioning领域是一个很重大的突破，打破了需要一大堆手工组件的现状。
        哥谭小市民我耐不住寂寞，顺着链接的仓库作者找到了您的github账号，现在每个星期都在关注我们哥谭市企业家的github是否更新了这篇文章的代码，盼望着这篇文章早日开源。

祝工作顺利        
哥谭小市民

**Comment by ch3cook-fdu** [comment]
感谢罗宾/夜翼，以及来自中心城、大都会的朋友对我们文章的关注和喜爱。非常抱歉由于本人前段时间在进行其他论文项目，暂时搁置了本论文的开源。目前该论文的所有代码可以通过 https://github.com/ch3cook-fdu/Vote2Cap-DETR 地址访问，如您遇到任何关于：复现、原理、论文或任何相关问题，欢迎以open issue，或是通过 csjch3cook@gmail.com 邮箱与我联系！
